# Generated by Django 4.2.5 on 2024-02-17 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0004_alter_profile_identifiant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifiant",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "dp",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.profile",
                        verbose_name="directeur_programme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programme",
                "verbose_name_plural": "Programmes",
            },
        ),
        migrations.CreateModel(
            name="module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifiant",
                    models.CharField(blank=True, max_length=110, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("groupe", models.PositiveIntegerField()),
                (
                    "charge_crs",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Les Modules",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifiant",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
                ("image_lesson", models.ImageField(blank=True, upload_to="image_crs/")),
                ("pdf_lesson", models.FileField(blank=True, upload_to="pdf_crs/")),
                ("video_lesson", models.FileField(blank=True, upload_to="video_crs/")),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.profile",
                    ),
                ),
                (
                    "domaine",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cours.programme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chapitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=20)),
                (
                    "lesson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cours.lesson",
                    ),
                ),
            ],
        ),
    ]
