# Generated by Django 4.2.5 on 2024-02-17 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0002_module_chapitre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapitre",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="domaine",
        ),
        migrations.RemoveField(
            model_name="module",
            name="chapitre",
        ),
        migrations.AddField(
            model_name="chapitre",
            name="module",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cours.module",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="chapitre",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cours.chapitre",
            ),
        ),
    ]
