# Generated by Django 4.2.5 on 2024-02-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_profile_identifiant"),
        ("cours", "0003_remove_chapitre_lesson_remove_lesson_domaine_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifiant",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("note", models.PositiveIntegerField()),
                (
                    "etudiant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.profile",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cours.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "note",
                "ordering": ["note"],
            },
        ),
    ]
