# Generated by Django 4.2.5 on 2024-02-18 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0004_note"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"verbose_name": "Module", "verbose_name_plural": "Modules"},
        ),
        migrations.AddField(
            model_name="module",
            name="programme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cours.programme",
            ),
        ),
    ]
