# Generated by Django 4.2.5 on 2024-02-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0006_alter_chapitre_identifiant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapitre",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
