# Generated by Django 4.2.5 on 2024-02-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0007_alter_chapitre_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapitre",
            name="identifiant",
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
