# Generated by Django 4.2.5 on 2024-02-21 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_profile_choices"),
        ("cours", "0012_alter_lesson_chapitre"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapitre",
            name="auteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.profile",
            ),
        ),
    ]
