# Generated by Django 4.2.5 on 2024-02-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0013_chapitre_auteur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapitre",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
