# Generated by Django 4.2.5 on 2024-02-25 03:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0015_alter_lesson_name_alter_module_name_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chapitre",
            unique_together={("name", "module")},
        ),
    ]
