# Generated by Django 4.2.5 on 2024-03-09 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_profile_domaine_programme"),
        ("cours", "0018_commentaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choix_Cours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifiant",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                (
                    "cours",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cours.module",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
            ],
            options={
                "verbose_name": "COURS&Etudiant",
                "verbose_name_plural": "COURS&Etudiants",
                "unique_together": {("cours", "user")},
            },
        ),
    ]
