# Generated by Django 4.2.5 on 2024-03-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0019_choix_cours"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="price",
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
