# Generated by Django 4.2.5 on 2024-03-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0020_module_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="module",
            name="groupe",
        ),
        migrations.AddField(
            model_name="choix_cours",
            name="groupe",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
