# Generated by Django 4.2.5 on 2024-03-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0021_remove_module_groupe_choix_cours_groupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="choix_cours",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="choix_cours",
            name="cours",
            field=models.CharField(max_length=500),
        ),
    ]
