# Generated by Django 4.2.5 on 2024-03-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0024_alter_note_options_alter_note_commentaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="image_module",
            field=models.ImageField(blank=True, null=True, upload_to="Image/module"),
        ),
    ]
