# Generated by Django 4.2.5 on 2024-04-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_rename_paie_profile_pai"),
        ("cours", "0027_payer_session_alter_payer_identifiant_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payer",
            old_name="module",
            new_name="modules",
        ),
        migrations.AlterUniqueTogether(
            name="payer",
            unique_together={("modules", "profile", "session")},
        ),
        migrations.AlterField(
            model_name="payer",
            name="identifiant",
            field=models.CharField(blank=True, max_length=400, unique=True),
        ),
    ]
