# Generated by Django 4.2.5 on 2024-04-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0029_alter_payer_identifiant"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="ecole",
            field=models.CharField(default="UQAC", max_length=300, null=True),
        ),
    ]
