# Generated by Django 4.2.5 on 2024-04-20 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0030_module_ecole"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="module",
            unique_together={("name", "ecole")},
        ),
    ]
