# Generated by Django 4.2.5 on 2024-04-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0031_alter_module_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="choix_cours",
            options={
                "verbose_name": "Choix_de_Cours",
                "verbose_name_plural": "Choix_de_Cours",
            },
        ),
        migrations.AddField(
            model_name="choix_cours",
            name="session",
            field=models.CharField(blank=True, default="Session Hiver", max_length=200),
        ),
    ]
