# Generated by Django 4.2.5 on 2024-05-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_rename_paie_profile_pai"),
        ("cours", "0032_alter_choix_cours_options_choix_cours_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="professeur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="professeur",
                to="user.profile",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="etudiant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Etudiant",
                to="user.profile",
            ),
        ),
    ]
