# Generated by Django 4.2.5 on 2024-05-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0033_note_professeur_alter_note_etudiant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="note",
            field=models.CharField(max_length=55),
        ),
    ]
