# Generated by Django 4.2.5 on 2024-05-01 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_rename_paie_profile_pai"),
        ("cours", "0034_alter_note_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="Planification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.CharField(blank=True, max_length=10)),
                ("session", models.CharField(default="Session Hiver", max_length=30)),
                (
                    "matiere",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cours.module",
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.profile",
                    ),
                ),
            ],
        ),
    ]
