# Generated by Django 4.2.5 on 2024-05-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_rename_paie_profile_pai"),
        ("cours", "0036_planification_ponderation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planification",
            options={
                "verbose_name": "Ponderation",
                "verbose_name_plural": "Ponderations",
            },
        ),
        migrations.AlterField(
            model_name="note",
            name="commentaire",
            field=models.CharField(default="Ceci est un commentaire", max_length=500),
        ),
        migrations.AlterField(
            model_name="planification",
            name="identifiant",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name="planification",
            unique_together={("professeur", "matiere")},
        ),
    ]
