# Generated by Django 4.2.5 on 2024-05-06 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0037_alter_planification_options_alter_note_commentaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planification",
            name="majoration",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="majoration",
            ),
            preserve_default=False,
        ),
    ]
