# Generated by Django 4.2.5 on 2024-05-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0038_planification_majoration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planification",
            name="majoration",
            field=models.CharField(
                max_length=255, null=True, verbose_name="majoration"
            ),
        ),
    ]
