# Generated by Django 4.2.5 on 2024-05-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0041_alter_planification_majoration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="note",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
