# Generated by Django 4.2.5 on 2024-05-09 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_rename_paie_profile_pai"),
        ("cours", "0042_alter_note_note"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={("module", "etudiant", "professeur")},
        ),
    ]
