# Generated by Django 4.2.5 on 2024-05-09 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0043_alter_note_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="note",
            unique_together=set(),
        ),
    ]
