# Generated by Django 4.2.5 on 2024-05-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_rename_paie_profile_pai"),
        ("cours", "0044_alter_note_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planification",
            options={
                "verbose_name": "Plannification",
                "verbose_name_plural": "Plannifications",
            },
        ),
        migrations.AddField(
            model_name="note",
            name="historique_changement",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={("module", "etudiant", "professeur")},
        ),
    ]
