# Generated by Django 4.2.5 on 2024-05-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_rename_paie_profile_pai"),
        ("cours", "0045_alter_planification_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identidiant", models.CharField(blank=True, max_length=10, null=True)),
                ("backup", models.JSONField()),
                (
                    "interesser",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.profile",
                    ),
                ),
            ],
        ),
    ]
