# Generated by Django 4.2.5 on 2024-05-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0046_historique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="historique_changement",
        ),
        migrations.AddField(
            model_name="note",
            name="moyenne",
            field=models.CharField(default=0, max_length=4),
        ),
    ]
