# Generated by Django 4.2.5 on 2024-05-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0047_remove_note_historique_changement_note_moyenne"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="moyenne",
            field=models.CharField(default=0, max_length=10),
        ),
    ]
