# Generated by Django 4.2.5 on 2024-05-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0048_alter_note_moyenne"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="session",
            field=models.CharField(default="Automne", max_length=50),
        ),
    ]
