# Generated by Django 4.2.5 on 2024-05-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0049_note_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="session",
            field=models.CharField(default="Automne 2024", max_length=50),
        ),
    ]
