# Generated by Django 4.2.5 on 2024-06-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0050_alter_note_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Create_groupe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifiant",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
            ],
        ),
    ]
