# Generated by Django 4.2.5 on 2024-06-03 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_remove_profile_code_secret_myuser_code_secret"),
        ("cours", "0051_create_groupe"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_groupe",
            name="concerne",
            field=models.CharField(default="[]", max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="create_groupe",
            name="name",
            field=models.CharField(default="", max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="create_groupe",
            name="note",
            field=models.CharField(default="", max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="create_groupe",
            name="professeur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.profile",
            ),
        ),
        migrations.AlterField(
            model_name="create_groupe",
            name="identifiant",
            field=models.CharField(
                blank=True, default="grp-1", max_length=30, unique=True
            ),
        ),
    ]
