# Generated by Django 4.2.5 on 2024-06-04 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0052_create_groupe_concerne_create_groupe_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_groupe",
            name="matiere",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cours.module",
            ),
        ),
        migrations.AlterField(
            model_name="create_groupe",
            name="concerne",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="create_groupe",
            name="note",
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
