# Generated by Django 4.2.5 on 2024-06-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0053_create_groupe_matiere_alter_create_groupe_concerne_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_groupe",
            name="document_file",
            field=models.FileField(blank=True, upload_to=""),
        ),
    ]
