# Generated by Django 4.2.5 on 2024-06-06 02:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0054_create_groupe_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="create_groupe",
            name="name",
        ),
    ]
