# Generated by Django 4.2.5 on 2024-06-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0055_remove_create_groupe_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="create_groupe",
            name="document_file",
        ),
        migrations.AlterField(
            model_name="create_groupe",
            name="concerne",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="create_groupe",
            name="identifiant",
            field=models.CharField(
                blank=True, default="grp-1", max_length=130, unique=True
            ),
        ),
    ]
