# Generated by Django 4.2.5 on 2024-06-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0057_create_groupe_examen_concerne_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_groupe",
            name="liste_date",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
