# Generated by Django 4.2.5 on 2024-06-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0058_create_groupe_liste_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_groupe",
            name="politique",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
