# Generated by Django 4.2.5 on 2024-06-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0059_create_groupe_politique"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_groupe",
            name="file_prof",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
