# Generated by Django 4.2.5 on 2024-06-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0059_create_groupe_politique"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_groupe",
            name="file_prof",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="create_groupe",
            name="recuperation",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="create_groupe",
            name="concerne",
            field=models.TextField(blank=True, null=True),
        ),
    ]
