# Generated by Django 4.2.5 on 2024-06-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0060_create_groupe_file_prof_create_groupe_recuperation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="create_groupe",
            name="concerne",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="create_groupe",
            name="recuperation",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
