# Generated by Django 4.2.5 on 2024-06-26 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0061_alter_create_groupe_concerne_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="create_groupe",
            name="recuperation",
        ),
        migrations.AlterField(
            model_name="create_groupe",
            name="concerne",
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
