# Generated by Django 4.2.5 on 2024-07-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_remove_profile_code_secret_myuser_code_secret"),
        ("cours", "0062_remove_create_groupe_recuperation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historique",
            name="backup",
            field=models.JSONField(default=list),
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={("module", "etudiant", "session")},
        ),
    ]
