# Generated by Django 4.2.5 on 2024-07-01 03:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0063_alter_historique_backup_alter_note_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historique",
            old_name="identidiant",
            new_name="identifiant",
        ),
    ]
