# Generated by Django 4.2.5 on 2024-07-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0064_rename_identidiant_historique_identifiant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historique",
            options={
                "verbose_name": "Backup/Poubelle",
                "verbose_name_plural": "Backups/Poubelles",
            },
        ),
        migrations.AlterField(
            model_name="historique",
            name="backup",
            field=models.JSONField(default=dict),
        ),
    ]
