# Generated by Django 4.2.5 on 2024-07-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0065_alter_historique_options_alter_historique_backup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payer",
            name="session",
            field=models.CharField(default="Automne 2024", max_length=100),
        ),
    ]
