# Generated by Django 4.2.5 on 2024-07-10 21:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_profile_is_suspend"),
        ("cours", "0066_alter_payer_session"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="choix_cours",
            unique_together={("user", "session")},
        ),
    ]
