# Generated by Django 4.2.5 on 2024-07-10 21:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0012_profile_is_suspend"),
        ("cours", "0067_alter_choix_cours_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="choix_cours",
            unique_together={("user", "session", "cours")},
        ),
    ]
