# Generated by Django 4.2.5 on 2024-07-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0068_alter_choix_cours_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planification",
            name="session",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
