# Generated by Django 4.2.5 on 2024-07-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0069_alter_planification_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="create_groupe",
            name="session",
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
