# Generated by Django 4.2.5 on 2024-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0070_create_groupe_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stocke_media_file",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant_file", models.CharField(blank=True, max_length=70)),
                ("type_file", models.CharField(max_length=255)),
                ("mon_fichier", models.FileField(upload_to="tp")),
            ],
            options={
                "verbose_name": "Stocke media",
            },
        ),
    ]
