# Generated by Django 4.2.5 on 2024-09-26 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cours", "0071_stocke_media_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="create_groupe",
            name="file_prof",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
