# Generated by Django 4.2.5 on 2024-02-07 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="myuser",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.CharField(max_length=15, unique=True)),
                (
                    "choices",
                    models.CharField(
                        choices=[
                            ("etudiant", "etudiant"),
                            ("charge_cours", "charge_cours"),
                            ("charger_td", "charger_td"),
                            ("employer_bureau", "employer_bureau"),
                        ],
                        max_length=90,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
