# Generated by Django 4.2.5 on 2024-02-07 04:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_myuser_managers_alter_myuser_email_profile"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="myuser",
            managers=[],
        ),
    ]
