# Generated by Django 4.2.5 on 2024-02-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_profile_identifiant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="choices",
            field=models.CharField(
                choices=[
                    ("etudiant", "etudiant"),
                    ("charge_cours", "charge_cours"),
                    ("charger_td", "charger_td"),
                    ("employer_bureau", "employer_bureau"),
                    ("responsable_pro", "responsable_pro"),
                ],
                max_length=90,
            ),
        ),
    ]
