# Generated by Django 4.2.5 on 2024-02-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_profile_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="choices",
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
