# Generated by Django 4.2.5 on 2024-03-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_profile_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="domaine_programme",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
