# Generated by Django 4.2.5 on 2024-03-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_profile_domaine_programme"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="paie",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
