# Generated by Django 4.2.5 on 2024-05-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0010_remove_profile_pai_profile_code_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="code_secret",
        ),
        migrations.AddField(
            model_name="myuser",
            name="code_secret",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
