# Generated by Django 4.2.5 on 2024-07-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_remove_profile_code_secret_myuser_code_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_suspend",
            field=models.BooleanField(default=False),
        ),
    ]
